version: '3.8'

services:
  pacs:
    build: ./orthanc
    ports:
      - "8042:8042"  # Orthanc Web interface
      - "4242:4242"  # DICOM port
    volumes:
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json
      - ./orthanc/plugins/python:/usr/share/orthanc/plugins/python
      - ./var/orthanc-storage:/var/lib/orthanc/db
      - ./var/worklists:/worklists

    environment:
      OHIF_PLUGIN_ENABLED: "false"
      PYTHON_PLUGIN_ENABLED: "true"
      ORTHANC__PYTHON_SCRIPT: "/usr/share/orthanc/plugins/python/plugin.py"
      # ORTHANC__NAME: "orthanc-python"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      # - ORTHANC__PYTHON_SCRIPT: "/python/convert-mp4-to-cine.py"
      ORTHANC__AUTHENTICATION_ENABLED: "false"      
      DICOM_WEB_PLUGIN_ENABLED: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      # ORTHANC__WORKLISTS__DATABASE: /worklists

  ris:
    image: nextgenhealthcare/connect
    ports:
      - "8443:8443"

  pacs-mwl-ris:
    image: orthancteam/python-orthanc-tools:0.10.0
    ports:
      - "2575:2575"
    volumes:
      - ./var/worklists:/worklists
    entrypoint: ["python", "-m", "orthanc_tools.hl7_worklist_server_for_orthanc"]

  # cheqd-studio:
  #   image: ghcr.io/cheqd/studio
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - cheqd-studio.env

  test-store:
    image: redis
    ports:
      - '6379:6379'
